name: Docker Image CI

on:
  push:
    branches: [ "2025-rewrite" ]
  pull_request:
    branches: [ "2025-rewrite" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract short commit hash
      run: echo "SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag octopusenergy-consumption-metrics:$SHORT_SHA
    - name: Save image tag for later steps
      run: echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_ENV
    - name: Save image as artifact (for next job)
      run: docker save octopusenergy-consumption-metrics:$IMAGE_TAG | gzip > image.tar.gz
    - uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar.gz

  push:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract short commit hash
      run: echo "SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - uses: actions/download-artifact@v4
      with:
        name: docker-image
    - name: Load the saved Docker image
      run: gunzip -c image.tar.gz | docker load
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Tag and Push the Docker image
      run: |
        docker tag octopusenergy-consumption-metrics:$IMAGE_TAG ghcr.io/octopusenergy/octopusenergy-consumption-metrics:$IMAGE_TAG
        docker push ghcr.io/octopusenergy/octopusenergy-consumption-metrics:$IMAGE_TAG
