name: Docker Image CI

on:
  push:
    branches: [ "2025-rewrite" ]
  pull_request:
    branches: [ "2025-rewrite" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag octopusenergy-consumption-metrics:$(date +%s)

  push:
    
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push the Docker image
      run: docker tag octopusenergy-consumption-metrics:$(date +%s) ghcr.io/octopusenergy/octopusenergy-consumption-metrics:$(date +%s)
    - run: docker push ghcr.io/octopusenergy/octopusenergy-consumption-metrics:$(date +%s)